import { Discussion } from "../types/models";

export const exampleDiscussions: Discussion[] = [
  {
    id: "disc1",
    userID: "user999",
    title: "Best boss fights in the game?",
    text: "What was your favorite boss and why? I loved the final one — such a challenge!",
    tags: ["boss-fights", "strategy"],
    gameID: "game001",
    comments: ["comm10", "comm11", "comm12"],
    date: new Date("2025-02-25T18:20:00Z"),
    likes: 95,
    dislikes: 3,
  },
  {
    id: "disc2",
    userID: "user555",
    title: "Multiplayer modes: Worth it?",
    text: "Thinking of getting the game mainly for online co-op. How's the experience?",
    tags: ["multiplayer", "co-op", "gameplay"],
    gameID: "game002",
    comments: ["comm13"],
    date: new Date("2025-03-14T11:15:00Z"),
    likes: 60,
    dislikes: 5,
  },
  {
    id: "disc3",
    userID: "user888",
    title: "Any good mods yet?",
    text: "Curious if anyone has seen cool mods pop up for this game. I’d love a graphic overhaul mod.",
    tags: ["mods", "community"],
    gameID: "game003",
    comments: [],
    date: new Date("2025-04-01T08:50:00Z"),
    likes: 33,
    dislikes: 1,
  },
];
