// Object: name → slug
export const IGDBgenres = [
  { slug: "adventure", name: "Adventure", id: 50 },
  { slug: "arcade", name: "Arcade", id: 52 },
  { slug: "card-board-game", name: "Card & Board Game", id: 54 },
  { slug: "fighting", name: "Fighting", id: 34 },
  { slug: "hack-and-slash", name: "Hack and slash/Beat 'em up", id: 47 },
  { slug: "indie", name: "Indie", id: 51 },
  { slug: "moba", name: "MOBA", id: 55 },
  { slug: "music", name: "Music", id: 36 },
  { slug: "pinball", name: "Pinball", id: 49 },
  { slug: "platform", name: "Platform", id: 37 },
  { slug: "point-and-click", name: "Point-and-click", id: 33 },
  { slug: "puzzle", name: "Puzzle", id: 38 },
  { slug: "quiz-trivia", name: "Quiz/Trivia", id: 48 },
  { slug: "racing", name: "Racing", id: 39 },
  { slug: "rts", name: "Real Time Strategy (RTS)", id: 40 },
  { slug: "rpg", name: "Role-playing (RPG)", id: 41 },
  { slug: "shooter", name: "Shooter", id: 35 },
  { slug: "simulator", name: "Simulator", id: 42 },
  { slug: "sport", name: "Sport", id: 43 },
  { slug: "strategy", name: "Strategy", id: 44 },
  { slug: "tactical", name: "Tactical", id: 46 },
  { slug: "tbs", name: "Turn-based strategy (TBS)", id: 45 },
  { slug: "visual-novel", name: "Visual Novel", id: 53 },
];
export const genreMap = Object.fromEntries(
  IGDBgenres.map((g) => [g.slug, g.id]),
);

// Object: name → slug
export const genres: Record<string, string> = {
  Adventure: "adventure",
  Arcade: "arcade",
  "Card & Board Game": "card-and-board-game",
  Fighting: "fighting",
  "Hack and slash/Beat 'em up": "hack-and-slash-beat-em-up",
  Indie: "indie",
  MOBA: "moba",
  Music: "music",
  Pinball: "pinball",
  Platform: "platform",
  "Point-and-click": "point-and-click",
  Puzzle: "puzzle",
  "Quiz/Trivia": "quiz-trivia",
  Racing: "racing",
  "Real Time Strategy (RTS)": "real-time-strategy-rts",
  "Role-playing (RPG)": "role-playing-rpg",
  Shooter: "shooter",
  Simulator: "simulator",
  Sport: "sport",
  Strategy: "strategy",
  Tactical: "tactical",
  "Turn-based strategy (TBS)": "turn-based-strategy-tbs",
  "Visual Novel": "visual-novel",
};

// Array of names
export const genreNames: string[] = [
  "Adventure",
  "Arcade",
  "Card & Board Game",
  "Fighting",
  "Hack and slash/Beat 'em up",
  "Indie",
  "MOBA",
  "Music",
  "Pinball",
  "Platform",
  "Point-and-click",
  "Puzzle",
  "Quiz/Trivia",
  "Racing",
  "Real Time Strategy (RTS)",
  "Role-playing (RPG)",
  "Shooter",
  "Simulator",
  "Sport",
  "Strategy",
  "Tactical",
  "Turn-based strategy (TBS)",
  "Visual Novel",
];
export const genreSlugs = [
  "adventure",
  "arcade",
  "card-and-board-game",
  "fighting",
  "hack-and-slash-beat-em-up",
  "indie",
  "moba",
  "music",
  "pinball",
  "platform",
  "point-and-click",
  "puzzle",
  "quiz-trivia",
  "racing",
  "real-time-strategy-rts",
  "role-playing-rpg",
  "shooter",
  "simulator",
  "sport",
  "strategy",
  "tactical",
  "turn-based-strategy-tbs",
  "visual-novel",
];
