// Object: name → slug
export const genres: Record<string, string> = {
  Adventure: "adventure",
  Arcade: "arcade",
  "Card & Board Game": "card-and-board-game",
  Fighting: "fighting",
  "Hack and slash/Beat 'em up": "hack-and-slash-beat-em-up",
  Indie: "indie",
  MOBA: "moba",
  Music: "music",
  Pinball: "pinball",
  Platform: "platform",
  "Point-and-click": "point-and-click",
  Puzzle: "puzzle",
  "Quiz/Trivia": "quiz-trivia",
  Racing: "racing",
  "Real Time Strategy (RTS)": "real-time-strategy-rts",
  "Role-playing (RPG)": "role-playing-rpg",
  Shooter: "shooter",
  Simulator: "simulator",
  Sport: "sport",
  Strategy: "strategy",
  Tactical: "tactical",
  "Turn-based strategy (TBS)": "turn-based-strategy-tbs",
  "Visual Novel": "visual-novel",
};

// Array of names
export const genreNames: string[] = [
  "Adventure",
  "Arcade",
  "Card & Board Game",
  "Fighting",
  "Hack and slash/Beat 'em up",
  "Indie",
  "MOBA",
  "Music",
  "Pinball",
  "Platform",
  "Point-and-click",
  "Puzzle",
  "Quiz/Trivia",
  "Racing",
  "Real Time Strategy (RTS)",
  "Role-playing (RPG)",
  "Shooter",
  "Simulator",
  "Sport",
  "Strategy",
  "Tactical",
  "Turn-based strategy (TBS)",
  "Visual Novel",
];
