import { Review } from "../types/models";

export const exampleReviews: Review[] = [
  {
    id: "rev1",
    userID: "user123",
    title: "Incredible story and gameplay!",
    text: "The plot twists were amazing and the combat system was smooth. Highly recommend to RPG fans.",
    rating: 5,
    gameID: "game001",
    comments: ["comm1", "comm2"],
    date: new Date("2024-11-12T14:30:00Z"),
    likes: 128,
    dislikes: 4,
  },
  {
    id: "rev2",
    userID: "user456",
    title: "Decent but buggy",
    text: "The game has potential but crashes too often. Waiting for future patches.",
    rating: 3.5,
    gameID: "game002",
    comments: ["comm3"],
    date: new Date("2025-01-03T09:00:00Z"),
    likes: 45,
    dislikes: 12,
  },
  {
    id: "rev3",
    userID: "user789",
    title: "Overhyped",
    text: "Graphics are top-notch, but the gameplay felt repetitive after a few hours.",
    rating: 2,
    gameID: "game003",
    comments: [],
    date: new Date("2025-04-18T20:45:00Z"),
    likes: 30,
    dislikes: 40,
  },
];
