// Object: name → slug
export const themes: Record<string, string> = {
  Action: "action",
  Business: "business",
  Comedy: "comedy",
  Drama: "drama",
  Educational: "educational",
  Erotic: "erotic",
  Fantasy: "fantasy",
  Historical: "historical",
  Horror: "horror",
  Kids: "kids",
  Mystery: "mystery",
  "Non-fiction": "non-fiction",
  "Open world": "open-world",
  Party: "party",
  Romance: "romance",
  Sandbox: "sandbox",
  "Science fiction": "science-fiction",
  Stealth: "stealth",
  Survival: "survival",
  Thriller: "thriller",
  Warfare: "warfare",
  "4X (explore, expand, exploit, and exterminate)":
    "4x-explore-expand-exploit-and-exterminate",
};

// Array of names
export const themeNames: string[] = [
  "Action",
  "Business",
  "Comedy",
  "Drama",
  "Educational",
  "Erotic",
  "Fantasy",
  "Historical",
  "Horror",
  "Kids",
  "Mystery",
  "Non-fiction",
  "Open world",
  "Party",
  "Romance",
  "Sandbox",
  "Science fiction",
  "Stealth",
  "Survival",
  "Thriller",
  "Warfare",
  "4X (explore, expand, exploit, and exterminate)",
];
