// Object: name → slug
// Object: name → slug
export const themes: Record<string, string> = {
  Action: "action",
  Business: "business",
  Comedy: "comedy",
  Drama: "drama",
  Educational: "educational",
  Erotic: "erotic",
  Fantasy: "fantasy",
  Historical: "historical",
  Horror: "horror",
  Kids: "kids",
  Mystery: "mystery",
  "Non-fiction": "non-fiction",
  "Open world": "open-world",
  Party: "party",
  Romance: "romance",
  Sandbox: "sandbox",
  "Science fiction": "science-fiction",
  Stealth: "stealth",
  Survival: "survival",
  Thriller: "thriller",
  Warfare: "warfare",
  "4X (explore, expand, exploit, and exterminate)":
    "4x-explore-expand-exploit-and-exterminate",
};

export const IGDBthemes = [
  { slug: "action", name: "Action", id: 1 },
  { slug: "business", name: "Business", id: 28 },
  { slug: "comedy", name: "Comedy", id: 27 },
  { slug: "drama", name: "Drama", id: 31 },
  { slug: "educational", name: "Educational", id: 34 },
  { slug: "erotic", name: "Erotic", id: 42 },
  { slug: "fantasy", name: "Fantasy", id: 17 },
  { slug: "historical", name: "Historical", id: 22 },
  { slug: "horror", name: "Horror", id: 19 },
  { slug: "kids", name: "Kids", id: 35 },
  { slug: "mystery", name: "Mystery", id: 43 },
  { slug: "non-fiction", name: "Non-fiction", id: 32 },
  { slug: "open-world", name: "Open world", id: 38 },
  { slug: "party", name: "Party", id: 40 },
  { slug: "romance", name: "Romance", id: 44 },
  { slug: "sandbox", name: "Sandbox", id: 33 },
  { slug: "sci-fi", name: "Science fiction", id: 18 },
  { slug: "stealth", name: "Stealth", id: 23 },
  { slug: "survival", name: "Survival", id: 21 },
  { slug: "thriller", name: "Thriller", id: 20 },
  { slug: "warfare", name: "Warfare", id: 39 },
  {
    slug: "4x",
    name: "4X (explore, expand, exploit, and exterminate)",
    id: 41,
  },
];
export const themeMap = Object.fromEntries(
  IGDBthemes.map((t) => [t.slug, t.id]),
);
export const themeSlugMap = Object.fromEntries(
  IGDBthemes.map((t) => [t.name, t.slug]),
);

// Array of names
export const themeSlugs = [
  "action",
  "business",
  "comedy",
  "drama",
  "educational",
  "erotic",
  "fantasy",
  "historical",
  "horror",
  "kids",
  "mystery",
  "non-fiction",
  "open-world",
  "party",
  "romance",
  "sandbox",
  "science-fiction",
  "stealth",
  "survival",
  "thriller",
  "warfare",
  "4x-explore-expand-exploit-and-exterminate",
];

export const themeNames: string[] = [
  "Action",
  "Business",
  "Comedy",
  "Drama",
  "Educational",
  "Erotic",
  "Fantasy",
  "Historical",
  "Horror",
  "Kids",
  "Mystery",
  "Non-fiction",
  "Open world",
  "Party",
  "Romance",
  "Sandbox",
  "Science fiction",
  "Stealth",
  "Survival",
  "Thriller",
  "Warfare",
  "4X (explore, expand, exploit, and exterminate)",
];
