// Object: name → slug
// Object: name → slug
export const themes: Record<string, string> = {
  Action: "action",
  Business: "business",
  Comedy: "comedy",
  Drama: "drama",
  Educational: "educational",
  Erotic: "erotic",
  Fantasy: "fantasy",
  Historical: "historical",
  Horror: "horror",
  Kids: "kids",
  Mystery: "mystery",
  "Non-fiction": "non-fiction",
  "Open world": "open-world",
  Party: "party",
  Romance: "romance",
  Sandbox: "sandbox",
  "Science fiction": "science-fiction",
  Stealth: "stealth",
  Survival: "survival",
  Thriller: "thriller",
  Warfare: "warfare",
  "4X (explore, expand, exploit, and exterminate)":
    "4x-explore-expand-exploit-and-exterminate",
};

export const IGDBthemes = [
  { name: "Action", id: 67 },
  { name: "Business", id: 76 },
  { name: "Comedy", id: 75 },
  { name: "Drama", id: 56 },
  { name: "Educational", id: 59 },
  { name: "Erotic", id: 65 },
  { name: "Fantasy", id: 68 },
  { name: "Historical", id: 73 },
  { name: "Horror", id: 70 },
  { name: "Kids", id: 60 },
  { name: "Mystery", id: 66 },
  { name: "Non-fiction", id: 57 },
  { name: "Open world", id: 61 },
  { name: "Party", id: 63 },
  { name: "Romance", id: 77 },
  { name: "Sandbox", id: 58 },
  { name: "Science fiction", id: 69 },
  { name: "Stealth", id: 74 },
  { name: "Survival", id: 72 },
  { name: "Thriller", id: 71 },
  { name: "Warfare", id: 62 },
  { name: "4X (explore, expand, exploit, and exterminate)", id: 64 },
];

// Array of names
export const themeSlugs = [
  "action",
  "business",
  "comedy",
  "drama",
  "educational",
  "erotic",
  "fantasy",
  "historical",
  "horror",
  "kids",
  "mystery",
  "non-fiction",
  "open-world",
  "party",
  "romance",
  "sandbox",
  "science-fiction",
  "stealth",
  "survival",
  "thriller",
  "warfare",
  "4x-explore-expand-exploit-and-exterminate",
];

export const themeNames: string[] = [
  "Action",
  "Business",
  "Comedy",
  "Drama",
  "Educational",
  "Erotic",
  "Fantasy",
  "Historical",
  "Horror",
  "Kids",
  "Mystery",
  "Non-fiction",
  "Open world",
  "Party",
  "Romance",
  "Sandbox",
  "Science fiction",
  "Stealth",
  "Survival",
  "Thriller",
  "Warfare",
  "4X (explore, expand, exploit, and exterminate)",
];
