import { User } from "../types/models";

export const exampleUsers: User[] = [
  {
    id: "01",
    avatar: "",
    username: "Littilemike",
    followers: [],
    following: [],
    // blocked
    //groups
    //polls
    email: "example@gmail.com",
    password: "password",
    bio: "Just a test user.",
    discussions: [],
    reviews: [],
    lists: [],
    favorites: {
      id: "fav-01",
      userID: "01",
      name: "Favorites",
      tags: [],
      visibility: "public",
      ranked: true,
      description: "My favorite games.",
      games: ["game-1", "game-2"],
    },
    likes: {
      id: "like-01",
      userID: "01",
      name: "Liked Games",
      tags: [],
      visibility: "public",
      ranked: false,
      description: "Games I liked.",
      games: ["game-3"],
    },
    played: {
      id: "played-01",
      userID: "01",
      name: "Played",
      tags: [],
      visibility: "private",
      ranked: false,
      description: "Games I've played.",
      games: [],
    },
    playing: {
      id: "playing-01",
      userID: "01",
      name: "Currently Playing",
      tags: [],
      visibility: "friends",
      ranked: false,
      description: "Games I’m playing now.",
      games: [],
    },
    wishlist: {
      id: "wishlist-01",
      userID: "01",
      name: "Wishlist",
      tags: [],
      visibility: "public",
      ranked: false,
      description: "Games I want to play.",
      games: ["game-4"],
    },
  },
];
